/**
 * Local stand-in for api.animetom.live — `npm run dev:mock`.
 *
 * Lets you run the whole site offline, and reproduces the two real failure
 * modes the player has to survive:
 *   • /cdn/hls/*  → 401 unless the request carries the animetom.live referer,
 *                   and never sends Access-Control-Allow-Origin (like R2).
 *   • /embed/*    → X-Frame-Options: SAMEORIGIN (refuses to be framed).
 *
 * Placeholder art lives in public/_dev (generated by generate-placeholders.mjs).
 *
 * Use it with:
 *   ANIMETOM_API_BASE=http://127.0.0.1:4010/api ALLOW_PRIVATE_TARGETS=1 npm run dev
 */
import http from "node:http";

const PORT = Number(process.env.PORT || 4010);
const SELF = `http://127.0.0.1:${PORT}`;

const TITLES = [
  ["مشوكو تينسي الموسم الثالث", "mushoku tensei iii", "mushoku-tensei-iii"],
  ["يوريكا القرن العشرين", "nijuuseiki denki mokuroku", "nijuuseiki-denki"],
  ["ون بيس", "one piece", "one-piece"],
  ["قاتل الشياطين", "kimetsu no yaiba", "kimetsu-no-yaiba"],
  ["جوجوتسو كايسن", "jujutsu kaisen", "jujutsu-kaisen"],
  ["هجوم العمالقة", "shingeki no kyojin", "shingeki-no-kyojin"],
  ["عائلة التجسس", "spy x family", "spy-x-family"],
  ["فرقة الإطفاء", "enen no shouboutai", "enen-no-shouboutai"],
  ["سحر العائد", "kikansha no mahou", "kikansha-no-mahou"],
  ["طوكيو ريفنجرز", "tokyo revengers", "tokyo-revengers"],
  ["جدار الجليد", "koori no jouheki", "koori-no-jouheki"],
  ["المحققة ماتت بالفعل", "tantei wa mou shindeiru", "tantei-wa-mou"],
];

const GENRES = ["أكشن", "مغامرات", "دراما", "خيال", "شونين", "كوميدي", "رومانسي"];

function animeAt(i) {
  const [ar, en, slug] = TITLES[i % TITLES.length];
  const episodes = [12, 24, 1100, 26, 47, 88, 25, 24, 13, 50, 12, 13][i % 12];
  return {
    _id: `anime-${i}`,
    slug,
    title: en,
    titleEnglish: en,
    titleArabic: ar,
    description:
      "قصة مشوّقة تتابع بطلاً يخوض رحلة مليئة بالمغامرات والمعارك، حيث يكتشف قدرات جديدة ويواجه أعداءً أقوياء في عالم واسع مليء بالأسرار.",
    coverImage: `/_dev/cover-${(i % 12) + 1}.png`,
    r2CoverImage: "",
    bannerImage: `/_dev/banner.png`,
    episodes,
    publishedEpisodes: episodes,
    status: i % 3 === 0 ? "ongoing" : "completed",
    genres: GENRES.slice(i % 3, (i % 3) + 4),
    year: 2020 + (i % 6),
    rating: Number((7 + (i % 30) / 10).toFixed(1)),
    type: i % 7 === 0 ? "Movie" : "TV",
    episodeDuration: "24 دقيقة",
    studio: "Studio KAI",
    author: "Koucha Agasawa",
    trailerUrl: "https://youtu.be/sWvfeHOkAOU",
    ageRating: { label: "PG-13 - +13" },
    createdAt: new Date(Date.now() - i * 864e5).toISOString(),
  };
}

const ANIME = Array.from({ length: 36 }, (_, i) => animeAt(i));
const bySlug = (slug) => ANIME.find((a) => a.slug === slug) || ANIME[0];

function episodeFor(anime, number) {
  const hls = `${SELF}/cdn/hls/${anime.slug}-${number}/master.m3u8`;
  return {
    _id: `${anime.slug}-ep-${number}`,
    animeId: anime._id,
    number,
    title: `الحلقة ${number}`,
    isPublished: true,
    isFiller: number % 9 === 0,
    views: 1200 + number * 7,
    qualities: ["720p", "480p"],
    servers: [
      {
        _id: `${anime.slug}-${number}-s1`,
        name: "AnimeTom HLS",
        embedUrl: hls,
        url: hls,
        type: "hls",
        isAnimeTom: true,
        priority: 100,
      },
      {
        _id: `${anime.slug}-${number}-s2`,
        name: "MEGA - FHD",
        embedUrl: `${SELF}/embed/${anime.slug}-${number}`,
        priority: 10,
      },
      // Upstream regularly returns placeholders with no URL at all:
      { _id: `${anime.slug}-${number}-s3`, name: "Google Drive - HD", embedUrl: "", url: "", priority: 10 },
      { _id: `${anime.slug}-${number}-s4`, name: "dailymotion - SD", embedUrl: "", url: "", priority: 0 },
    ],
    downloadLinks: [
      { text: "mediafire", url: "https://www.mediafire.com/file/demo", quality: "720p" },
      { text: "gofile", url: "https://gofile.io/d/demo", quality: "480p" },
    ],
    createdAt: new Date(Date.now() - number * 36e5).toISOString(),
  };
}

function json(res, body, status = 200) {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Content-Length": Buffer.byteLength(payload),
  });
  res.end(payload);
}

function paginate(items, page, limit) {
  const start = (page - 1) * limit;
  return {
    data: items.slice(start, start + limit),
    pagination: {
      currentPage: page,
      totalPages: Math.max(1, Math.ceil(items.length / limit)),
      totalResults: items.length,
      totalCount: items.length,
      hasNextPage: start + limit < items.length,
      hasPrevPage: page > 1,
      limit,
    },
  };
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url, SELF);
  const p = url.pathname;
  const q = url.searchParams;
  const page = Number(q.get("page") || 1);
  const limit = Number(q.get("limit") || 24);

  let m;

  /* ---------------------------- media (R2-like) --------------------------- */
  if (p.startsWith("/cdn/")) {
    const referer = req.headers.referer || "";
    if (!referer.includes("animetom.live")) {
      res.writeHead(401, { "Content-Type": "text/html" });
      return res.end("<h1>Error 401</h1><p>This bucket cannot be viewed</p>");
    }
    // NOTE: deliberately no Access-Control-Allow-Origin header.
    if (p.endsWith("master.m3u8")) {
      const base = p.replace("master.m3u8", "");
      res.writeHead(200, { "Content-Type": "application/vnd.apple.mpegurl" });
      return res.end(
        [
          "#EXTM3U",
          "#EXT-X-VERSION:3",
          "#EXT-X-STREAM-INF:BANDWIDTH=2200000,RESOLUTION=1280x720",
          `${base}720p/index.m3u8`,
          "#EXT-X-STREAM-INF:BANDWIDTH=900000,RESOLUTION=854x480",
          `${base}480p/index.m3u8`,
          "",
        ].join("\n")
      );
    }
    if (p.endsWith("index.m3u8")) {
      res.writeHead(200, { "Content-Type": "application/vnd.apple.mpegurl" });
      return res.end(
        ["#EXTM3U", "#EXT-X-VERSION:3", "#EXT-X-TARGETDURATION:6", "#EXT-X-ENDLIST", ""].join("\n")
      );
    }
    res.writeHead(404);
    return res.end();
  }

  /* ------------------------- un-frameable embed page ---------------------- */
  if (p.startsWith("/embed/")) {
    res.writeHead(200, {
      "Content-Type": "text/html; charset=utf-8",
      "X-Frame-Options": "SAMEORIGIN",
    });
    return res.end(
      `<html style="background:#000;color:#fff;font-family:sans-serif"><body style="display:grid;place-items:center;height:100vh;margin:0"><p>مشغّل خارجي تجريبي</p></body></html>`
    );
  }

  /* -------------------------------- API ----------------------------------- */
  if (p === "/api/anime/featured-episodes") {
    return json(res, {
      success: true,
      data: ANIME.slice(0, 8).map((a, i) => ({
        _id: `feat-${i}`,
        title: a.title,
        titleArabic: a.titleArabic,
        description: a.description,
        coverImage: a.coverImage,
        bannerImage: a.bannerImage,
        year: a.year,
        genres: a.genres,
        status: a.status,
        rating: a.rating,
        episodeNumber: (i % 12) + 1,
        episodeId: `feat-ep-${i}`,
        animeSlug: a.slug,
      })),
    });
  }

  if (p === "/api/anime/latest-episodes") {
    const items = Array.from({ length: 60 }, (_, i) => {
      const a = ANIME[i % ANIME.length];
      return {
        _id: `late-${i}`,
        number: ((i * 3) % 24) + 1,
        title: `الحلقة ${((i * 3) % 24) + 1}`,
        views: 400 + i * 13,
        createdAt: new Date(Date.now() - i * 36e5).toISOString(),
        animeId: {
          _id: a._id,
          title: a.title,
          titleArabic: a.titleArabic,
          coverImage: a.coverImage,
          status: a.status,
          rating: a.rating,
          slug: a.slug,
        },
      };
    });
    return json(res, { success: true, ...paginate(items, page, limit) });
  }

  if (p === "/api/anime/seasonal") {
    return json(res, { success: true, data: ANIME.slice(0, 14) });
  }

  if (p === "/api/anime/search/suggestions") {
    const term = (q.get("q") || "").toLowerCase();
    return json(res, {
      success: true,
      data: ANIME.filter(
        (a) => a.title.includes(term) || a.titleArabic.includes(term)
      ).slice(0, 8),
    });
  }

  if (p === "/api/anime/search") {
    const term = (q.get("q") || "").toLowerCase();
    const items = ANIME.filter(
      (a) => a.title.includes(term) || a.titleArabic.includes(term)
    );
    return json(res, { success: true, ...paginate(items, page, limit) });
  }

  if (p === "/api/anime") {
    let items = ANIME;
    const type = q.get("type");
    if (type) items = items.filter((a) => a.type === type);
    const status = q.get("status");
    if (status) items = items.filter((a) => a.status === status);
    const genres = (q.get("genres") || "").split(",").filter(Boolean);
    if (genres.length) {
      items = items.filter((a) => genres.every((g) => a.genres.includes(g)));
    }
    return json(res, { success: true, ...paginate(items, page, limit) });
  }

  m = p.match(/^\/api\/anime\/external-data\/(.+)$/);
  if (m) {
    return json(res, {
      success: true,
      data: {
        characters: Array.from({ length: 8 }, (_, i) => ({
          id: i,
          name: `شخصية ${i + 1}`,
          image: `/_dev/cover-${(i % 12) + 1}.png`,
        })),
      },
    });
  }

  m = p.match(/^\/api\/anime\/([^/]+)\/episodes\/(\d+)$/);
  if (m) {
    return json(res, { success: true, data: episodeFor(bySlug(m[1]), Number(m[2])) });
  }

  m = p.match(/^\/api\/anime\/([^/]+)\/all-episodes$/);
  if (m) {
    const anime = bySlug(m[1]);
    const count = Math.min(anime.episodes, 60);
    return json(res, {
      success: true,
      data: Array.from({ length: count }, (_, i) => episodeFor(anime, i + 1)),
    });
  }

  m = p.match(/^\/api\/anime\/([^/]+)\/episode-count$/);
  if (m) return json(res, { success: true, data: { count: bySlug(m[1]).episodes } });

  m = p.match(/^\/api\/anime\/([^/]+)$/);
  if (m) {
    return json(res, {
      success: true,
      data: { anime: bySlug(m[1]), relations: ANIME.slice(1, 7) },
    });
  }

  json(res, { success: false, message: `Can't find this route: ${p}` }, 404);
});

server.listen(PORT, "127.0.0.1", () => {
  console.log(`[mock api] listening on ${SELF}`);
});
